version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - gitea
      - grafana
      - authelia
    networks:
      - internal      

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    expose:
      - "3000"
    networks:
      - internal

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.localhost
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - "3000"
    networks:
      - internal

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: always
    volumes:
      - ./authelia/configuration.yml:/config/configuration.yml
      - ./authelia/users.yml:/config/users.yml
    expose:
      - "9091"
    environment:
      - TZ=Asia/Kolkata
    networks:
      - internal

volumes:
  gitea_data:
  grafana_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
